# 파이토치 2 autograd 와 Variable

In [2]:
import torch
from torch.autograd import Variable
a=torch.rand(5)
a=Variable

In [4]:
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [5]:
a = Variable(a, requires_grad = True)
print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [7]:
print("------a.data------")
print(a.data)
print("------a.grad------")
print(a.grad)
print("------a.grad_fn------")
print(a.grad_fn)

------a.data------
tensor([[1., 1.],
        [1., 1.]])
------a.grad------
None
------a.grad_fn------
None


In [8]:
b = a+2
print(b)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [9]:
c = b**2
print(c)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)


In [10]:
out = c.sum()
print(out)

tensor(36., grad_fn=<SumBackward0>)


In [11]:
print(out)
out.backward()

tensor(36., grad_fn=<SumBackward0>)


In [12]:
x=torch.ones(3)
x=Variable(x,requires_grad=True)
y=(x**2)
z=y*3
print(z)
grad = torch.Tensor([0.1,1,10])
z.backward(grad)

tensor([3., 3., 3.], grad_fn=<MulBackward0>)


In [14]:
print("---x.data---")
print(x.data)
print("---x.grad---")
print(x.grad)
print("---x.grad_fn---")
print(x.grad_fn)

---x.data---
tensor([1., 1., 1.])
---x.grad---
tensor([ 0.6000,  6.0000, 60.0000])
---x.grad_fn---
None
