In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [5]:
model = nn.Sequential(
    nn.Linear(2,1),
    nn.Sigmoid()
)

In [6]:
model(x_train)

tensor([[0.4020],
        [0.4147],
        [0.6556],
        [0.5948],
        [0.6788],
        [0.8061]], grad_fn=<SigmoidBackward>)

In [11]:
optimizer = optim.SGD(model.parameters(),lr=1)

In [12]:
nb_epochs = 1000

for epoch in range(nb_epochs+1):
    hypothesis = model(x_train)
    cost = F.binary_cross_entropy(hypothesis,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5]) # 예측값이 0.5를 넘으면 True로 간주
        correct_prediction = prediction.float() == y_train # 실제값과 일치하는 경우만 True로 간주
        accuracy = correct_prediction.sum().item() / len(correct_prediction) # 정확도를 계산
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format( # 각 에포크마다 정확도를 출력
            epoch, nb_epochs, cost.item(), accuracy * 100,
        ))


Epoch    0/1000 Cost: 0.539226 Accuracy 83.33%
Epoch   10/1000 Cost: 0.596019 Accuracy 66.67%
Epoch   20/1000 Cost: 0.443233 Accuracy 66.67%
Epoch   30/1000 Cost: 0.373563 Accuracy 83.33%
Epoch   40/1000 Cost: 0.316691 Accuracy 83.33%
Epoch   50/1000 Cost: 0.266393 Accuracy 83.33%
Epoch   60/1000 Cost: 0.220765 Accuracy 100.00%
Epoch   70/1000 Cost: 0.182298 Accuracy 100.00%
Epoch   80/1000 Cost: 0.157408 Accuracy 100.00%
Epoch   90/1000 Cost: 0.144158 Accuracy 100.00%
Epoch  100/1000 Cost: 0.134328 Accuracy 100.00%
Epoch  110/1000 Cost: 0.125818 Accuracy 100.00%
Epoch  120/1000 Cost: 0.118341 Accuracy 100.00%
Epoch  130/1000 Cost: 0.111719 Accuracy 100.00%
Epoch  140/1000 Cost: 0.105813 Accuracy 100.00%
Epoch  150/1000 Cost: 0.100514 Accuracy 100.00%
Epoch  160/1000 Cost: 0.095732 Accuracy 100.00%
Epoch  170/1000 Cost: 0.091395 Accuracy 100.00%
Epoch  180/1000 Cost: 0.087443 Accuracy 100.00%
Epoch  190/1000 Cost: 0.083827 Accuracy 100.00%
Epoch  200/1000 Cost: 0.080506 Accuracy 100.00

In [13]:
model(x_train)


tensor([[2.7620e-04],
        [3.1596e-02],
        [3.8961e-02],
        [9.5623e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward>)

In [14]:
print(list(model.parameters()))


[Parameter containing:
tensor([[3.2534, 1.5181]], requires_grad=True), Parameter containing:
tensor([-14.4837], requires_grad=True)]
